version: '3'
services:
  node_backend:
    container_name: node_backend
    build: ./employee-management-system/
    depends_on:
      - pg
    ports:
      - '3001:3000'
    volumes:
      - './employee-management-system:/home/node/app'
    command: npm start
    restart: always
#   stdin_open: true

  pg:
    image: 'postgres:12'
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: employee_main_db
    ports:
      - '5432:5432'
    volumes:
      - './ems_pg_data/db_data:/var/lib/postgresql/data'
